// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import Sidebar from "./components/Sidebar";
import NavigationBar from "./components/NavigationBar";
import Footer from "./components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-slate-950'>
      <body className="dark text-black flex w-[100%] h-screen relative" >
        <Sidebar />
        <main className="w-[82.5%] h-full bg-white relative left-[17.5%] top-0 z-40">

          <Provider>
            <img src="/logo-transparent-with-pic.jpg" className="w-full  h-[200px]" />
            <NavigationBar />
            <div className="w-full bg-white ">{children}</div>
            <Footer />

          </Provider>
        </main>
      </body>
    </html>
  );
}
