// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
import { Card, CardHeader, CardBody, CardFooter, Avatar, Button } from "@nextui-org/react";
import Link from "next/link";
import { FaStar } from "react-icons/fa";

import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import Sidebar from "./components/Sidebar";
import NavigationBar from "./components/NavigationBar";
// import Footer from "./components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-slate-950'>
      <body className="dark text-black flex w-[100%] h-screen relative" >
        <Sidebar />
        <main className="w-[82.5%] h-full bg-white relative left-[17.5%] top-0 z-40">

          <Provider>
            <img src="/logo-transparent-with-pic.jpg" className="w-full  h-[200px]" />
            <NavigationBar />
            <div className="w-full bg-white ">{children}</div>
            <>
              <div className="w-full h-fit bg-[#4E31AA] border-gray-800 border-t-1 p-10 flex flex-col justify-center items-center">
                <Card className="max-w-[340px]">
                  <CardHeader className="justify-center">
                    <div className="flex flex-col justify-center items-center gap-5">
                      <Avatar isBordered radius="full" size="md" src="https://nextui.org/avatars/avatar-1.png" />
                      <div className="flex flex-col gap-1 items-start justify-center">
                        <h4 className="text-small font-semibold leading-none text-default-600">Zoey Lang</h4>
                        <h5 className="text-small tracking-tight text-default-400">@zoeylang</h5>
                      </div>
                    </div>

                  </CardHeader>
                  <CardBody className="px-3 py-0 text-small text-default-400">
                    <p>
                      Frontend developer and UI/UX enthusiast. Join me on this coding adventure!
                    </p>
                  </CardBody>
                  <CardFooter className="flex gap-1">
                    <FaStar className="text-orange-500 w-5 h-5" />
                    <FaStar className="text-orange-500 w-5 h-5" />
                    <FaStar className="text-orange-500 w-5 h-5" />
                    <FaStar className="text-orange-500 w-5 h-5" />
                    <FaStar className="text-orange-500 w-5 h-5" />

                  </CardFooter>
                </Card>
              </div>
              <div className="w-full h-fit bg-[#4E31AA] border-gray-800 border-t-1 p-10 flex justify-center items-center">
                <div className="flex justify-between items-center">
                  <div className="text-white text-center flex flex-col text-2xl flex[0.5]">
                    <Link href="#">Home</Link>
                    <Link href="#">Service Policy and About Us</Link>
                    <Link href="#">Contact Us</Link>
                  </div>
                  <div className="text-white text-center flex flex-col text-2xl flex[0.5]">
                    <Link href="#">Home</Link>
                    <Link href="#">Service Policy and About Us</Link>
                    <Link href="#">Contact Us</Link>
                  </div>
                </div>
              </div>
            </>
          </Provider>
        </main>
      </body>
    </html>
  );
}
